# footprint: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]]
footprint: [[-0.25, -0.28], [0.25, -0.28], [0.25, 0.28], [-0.25, 0.28]]
footprint_padding: 0.1

robot_base_frame: base_link
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.5

resolution: 0.05

# maximum range sensor reading
obstacle_range: 5.5
# obstacle_range: 3.0
# freespace given a sensor reading
raytrace_range: 6.0
# raytrace_range: 4.0

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true}

inflation:
    # radius in meters to which the map inflates obstacle cost values.
    # inflation_radius: 1.0
    inflation_radius: 2.0
    # A scaling factor to apply to cost values during inflation
    # increasing the factor will decrease the resulting cost values
    # cost_scaling_factor: 10.0
    cost_scaling_factor: 6.5
