# throttle_scans: 1
# base_frame: base_link
# map_frame: map
# odom_frame: odom
# map_update_interval: 5.0
maxUrange: 20.0
sigma: 0.015
# kernelSize: 1
lstep: 0.025
astep: 0.015
# iterations: 5
lsigma: 0.015
ogain: 0.5
# lskip: 0
minimumScore: 500.0
srr: 0.025
srt: 0.075
str: 0.025
stt: 0.075
linearUpdate: 0.5
angularUpdate: 0.10
# temporalUpdate: -1.0
resampleThreshold: 5.0
particles: 60
xmin: -51.2 # NO TOUCH
ymin: -51.2 # NO TOUCH
xmax: 51.2 # NO TOUCH
ymax: 51.2 # NO TOUCH
# delta: 0.05
# llsamplerange: 0.01
# llsamplestep: 0.01
lasamplerange: 0.0015
lasamplestep: 0.0015
# transform_publish_period: 0.05
# occ_thresh: 0.25
# maxRange: ""
